---
output:
  github_document: default
  pdf_document: default
---

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-"
)
```

## Data and code from: Can chicks smell their parents? No evidence of olfactory parent recognition in a shorebird

Marc Gilles, Sama Zefania, Tafitasoa J. Mijoro, Innes C. Cuthill, Tamás Székely & Barbara A. Caspers

***

#### Overview of the repository content

#### Data  

The data was prepared in two datasets: one in horizontal format (one row = one trial) for the analysis, and one in vertical format (one row = one odour in a trial) for the plot.

* **`ymazeplovers_data_horizontal.csv`** contains the data for running the analysis in R (with description of variables in **`ymazeplovers_data_horizontal_description.xlsx`** )
* **`ymazeplovers_data_vertical.csv`** contains the data for drawing the plot in R (with description of variables in **`ymazeplovers_data_vertical_description.xlsx`** ). 

#### R code

* **`ymazeplovers_rmd.pdf`** and **`ymazeplovers_rmd.Rmd`** are Rmd documents describing the code used for the analyses in R.

